project:
  type: website
  output-dir: docs
  
website:
  title: "Reilly's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: www.linkedin.com/in/reilly-richardson-065039268 
      - icon: github
        href: https://github.com/rer1030/reillyswebsite.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Reilly Richardson"

format:
  html:
    theme: solar
    toc: true

editor: source

